version: '2'

services:
    adaguc-viewer:
        image: adaguc-viewer
        container_name: adaguc-viewer
        ports: 
            - "8081:80"
    adaguc-server:
        image: adaguc-server
        container_name: adaguc-server
        ports: 
            - "8080:8080"
        volumes:
            - $HOME/data/adaguc-datasets:/data/adaguc-datasets
            - $HOME/data/adaguc-autowms:/data/adaguc-autowms
        environment:
            - "EXTERNALADDRESS=http://127.0.0.1:8080/"

# Do docker-compose up in working directory
# Directories $HOME/data/adaguc-datasets and $HOME/data/adaguc-autowms will be created if they do not exist.
# Copy your NetCDF/GeoJSON/HDF5 to $HOME/data/adaguc-autowms
# Files are are accessible via http://localhost:8080/adaguc-services/wms.cgi?source=testdata.nc&&service=WMS&request=GetCapabilities
# They can be visited in the adaguc-viewer via: 
# http://localhost:8081/adaguc-viewer/ by adding service http://localhost:8080/adaguc-services/wms.cgi?source=testdata.nc via Add data.
#Direct link is:
# http://localhost:8081/adaguc-viewer/?service=http%3A%2F%2Flocalhost%3A8080%2Fadaguc-services%2Fwms.cgi%3Fsource%3Dtestdata.nc
# Testdata can be found here: http://opendap.knmi.nl/knmi/thredds/catalog/ADAGUC/catalog.html
